### PR TITLE
Add "textfield size" proof

### PR DESCRIPTION
**Pull request by T1mL3arn**
New FlxText snippet in continuation of this [review](https://github.com/HaxeFlixel/flixel/pull/2789#discussion_r1218295932).

### CODE REVIEW

**Comment by Geokureli** [comment]
when I saw this I thought it referred to the `text.size` property, not `fieldWidth`, `fieldHeight` and `autoSize` fields. I think the naming should be changed to "Textfield Auto Sizing" or something

**Comment by Geokureli** [comment]
what are your thoughts on this:
```hx
package states;

import flixel.FlxG;
import flixel.FlxState;
import flixel.util.FlxColor;
import flixel.text.FlxText;
import flixel.tweens.FlxTween;

class PlayState extends FlxState
{
	override function create()
	{
		super.create();
		
		bgColor = 0;

		var autoSizedText = new MorphingText("This text has an ", "auto width and height");
		autoSizedText.screenCenter(X);
		autoSizedText.y = 30;
		add(autoSizedText);

		var fixedSize = new MorphingText("This text has a ", "fixed width and height");
		fixedSize.fieldWidth = 140;
		fixedSize.fieldHeight = 70;
		fixedSize.screenCenter(X);
		fixedSize.y = autoSizedText.getScreenBounds().bottom + 10;
		add(fixedSize);

		var autoHeight = new MorphingText("This text has a ", "fixed width\nand auto height");
		autoHeight.fieldWidth = 100;
		autoHeight.fieldHeight = 0;
		autoHeight.screenCenter(X);
		autoHeight.y = fixedSize.getScreenBounds().bottom + 10;
		add(autoHeight);
		
		var autoWidth = new MorphingText("This text has a ", "fixed height\nand auto width");
		autoWidth.fieldWidth = 0;
		autoWidth.fieldHeight = 100;
		autoWidth.screenCenter(X);
		autoWidth.y = autoHeight.getScreenBounds().bottom + 10;
		add(autoWidth);
	}
}

/**
 * A helper class for a FlxText with a dark blue background, cyan text and ever-changing text
 */
@:forward
abstract MorphingText(FlxText) to FlxText
{
	/**
	 * @param   morphingText  The text that disappears and reappears
	 * @param   staticText    The text that always shows
	 * @param   size          The size of the text
	 */
	public function new (morphingText:String, staticText:String, size = 16)
	{
		this = new FlxText(0, 0, 0, morphingText + staticText, size);
		colorize();
		
		FlxTween.num(0, 1, 1.0, { loopDelay: 1.0, type: PINGPONG }, function(num)
		{
			this.text = morphingText.substr(0, Math.round(morphingText.length * num)) + staticText;
		});
	}
	
	function colorize()
	{
		this.color = FlxColor.CYAN;
		// accessing background through underlying openfl TextField object
		this.textField.background = true;
		this.textField.backgroundColor = 0x0C365F;
	}
}
```
This shows how each field reacts to different amounts of text and also adds fixed-height/auto-width, but it might be overly complicated
https://github.com/HaxeFlixel/snippets.haxeflixel.com/assets/2609513/cb6ff302-48fd-45a6-b443-c2455d9d9abd

**Comment by T1mL3arn** [comment]
I though about similar more advanced example but decided to follow rules from wiki "be as simple as possible". Overall idea to show how textfields react to updating their text is really good, but I think it should be user-triggered and without tween, something like simple switch between long and short text strings.

Also note 4-th "fixed height and auto width" does not work, such textfields behave the same as autosized, you can `trace(autoWidth.textField.height);` and see it is not `100`;

**Comment by Geokureli** [comment]
yeah maybe a button to append some text is a better approach

**Pull request merged**
