### PR TITLE
improve read me!

### PR DESCRIPTION
**Pull request by MrClogsworthYT**
now once you click on the logo you got to the site

### CODE REVIEW

**Comment by Geokureli** [comment]
when i preview the new file clicking doesn't seem to work like it did for the other changes

**Comment by MrClogsworthYT** [comment]
> when i preview the new file clicking doesn't seem to work like it did for the other changes. i think you need the `https://`?
> 
> Also the link only works for the icon, not the text, another difference from your other commits.

oops! ill fix this in a bit

**Comment by MrClogsworthYT** [comment]
> when i preview the new file clicking doesn't seem to work like it did for the other changes. i think you need the `https://`?
> 
> Also the link only works for the icon, not the text, another difference from your other commits.

the only reason the text doesn't do anything is because it isn't a part of the image only a seperate text and i didn't want the text to be blue

**Comment by MrClogsworthYT** [comment]
anyways this good?

**Comment by Geokureli** [comment]
you're right, I don't like the blue text, the other pages seem to include the text in the image. is that something we could do?

**Comment by MrClogsworthYT** [comment]
> you're right, I don't like the blue text, the other pages seem to include the text in the image. is that something we could do?

We could add the text to the image (easiest way) and use the github font

**Comment by MrClogsworthYT** [comment]
ok found the font now to make the image...

**Comment by MrClogsworthYT** [comment]
which is better this?
Untitled131_20220325001929

or this:
Untitled131_20220325001817

**Comment by Geokureli** [comment]
I was expecting something like the other githubs
image

**Comment by MrClogsworthYT** [comment]
> I was expecting something like the other githubs image
> 
> Edit: snippets.haxeflixel.com is much longer tho so maybe just make it smaller

alright a resizer should do the trick

**Comment by MrClogsworthYT** [comment]
> I was expecting something like the other githubs image
> 
> Edit: snippets.haxeflixel.com is much longer tho so maybe just make it smaller

is it alright if I make the text "Haxeflixel snippets"?

**Comment by Geokureli** [comment]
that works

**Comment by MrClogsworthYT** [comment]
> that works

Alrighty!

**Comment by MrClogsworthYT** [comment]
this good?

**Comment by Geokureli** [comment]
I prefer it to match the font and casing of the other repos
here's the font: https://fonts.google.com/specimen/Ubuntu

**Comment by MrClogsworthYT** [comment]
I dunno why but my editor refused to use the actual font so I had to get close to the font and this is the closest I can get 
Untitled133_20220325223508

**Comment by Geokureli** [comment]
let me try, I've asked you to make like 11 changes here and I appreciate you sticking with it

**Comment by Geokureli** [comment]
I'm thinking about going with 1 liners for all these, what do you think?
demos_1line
dev_1line
snippets_1line

**Comment by Geokureli** [comment]
snippets_1line
there we go!

**Comment by MrClogsworthYT** [comment]
> I'm thinking about going with 1 liners for all these, what do you think? demos_1line dev_1line snippets_1line just realized the icon is wrong for all of these, 1 sec

Cool!

**Comment by MrClogsworthYT** [comment]
> I'm thinking about going with 1 liners for all these, what do you think? demos_1line dev_1line snippets_1line just realized the icon is wrong for all of these, 1 sec

Cool Makes it look legit tbh anyways this pr should be good to go now

**Comment by MrClogsworthYT** [comment]
@Geokureli ?

**Pull request merged**
