### PR TITLE
fixing issues with flash build

### PR DESCRIPTION
**Pull request by SeiferTim**

### CODE REVIEW

**Comment by Geokureli** [comment]
there's also errors in `autotiles`

  source/PlayState.hx:35: characters 22-41 : Cannot skip non-nullable argument X
  source/PlayState.hx:44: characters 10-28 : Cannot skip non-nullable argument X
  source/PlayState.hx:53: characters 10-29 : Cannot skip non-nullable argument X

**Comment by Geokureli** [comment]
builds are failing, not sure why, but these demos compile for me locally on html5/flash so I'm merging

**Comment by SeiferTim** [comment]
Why are we building for flash when we don't support it on the site anymore?
Could that be removed from CI? Or switched to HTML5? (not sure how the CI is setup)

**Comment by Geokureli** [comment]
Dropping flixel's flash support is a big discussion. I don't think I want to drop it, just so we can avoid some caveats with optional args. 

Right now flixel CI test flash, html5, cpp, neko, and hashlink. each gets tested on haxe versions 4.0.5, latest(4.2.4), and nightly(dev). each test runs all the unit tests, demos and snippets with that version on that target. eventually we may need to reassess this, but there are projects out there with the goal of "reviving" the use of swfs in web.

**Pull request merged**
